Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 247, in insert_movie
    movie_release_date=movie['movie_release_date'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 260, in insert_movie_to_actor
    mysql_cursor.executemany(insert_movie_to_actor_command, movie_to_actor_list)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 192, in executemany
    self._get_db().encoding)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 229, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1062, u"Duplicate entry '1298274-1343703' for key 'PRIMARY'")
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 271, in insert_movie_to_director
    mysql_cursor.executemany(insert_movie_to_director_command, movie_to_director_list)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 192, in executemany
    self._get_db().encoding)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 229, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1062, u"Duplicate entry '1298274-1315228' for key 'PRIMARY'")
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 247, in insert_movie
    movie_release_date=movie['movie_release_date'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 260, in insert_movie_to_actor
    mysql_cursor.executemany(insert_movie_to_actor_command, movie_to_actor_list)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 192, in executemany
    self._get_db().encoding)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 229, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1062, u"Duplicate entry '1298274-1343703' for key 'PRIMARY'")
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 271, in insert_movie_to_director
    mysql_cursor.executemany(insert_movie_to_director_command, movie_to_director_list)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 192, in executemany
    self._get_db().encoding)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 229, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1062, u"Duplicate entry '1298274-1315228' for key 'PRIMARY'")
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 247, in insert_movie
    movie_release_date=movie['movie_release_date'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 260, in insert_movie_to_actor
    mysql_cursor.executemany(insert_movie_to_actor_command, movie_to_actor_list)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 192, in executemany
    self._get_db().encoding)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 229, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1062, u"Duplicate entry '1298274-1343703' for key 'PRIMARY'")
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 271, in insert_movie_to_director
    mysql_cursor.executemany(insert_movie_to_director_command, movie_to_director_list)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 192, in executemany
    self._get_db().encoding)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 229, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1062, u"Duplicate entry '1298274-1315228' for key 'PRIMARY'")
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 247, in insert_movie
    movie_release_date=movie['movie_release_date'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 282, in insert_movie_to_genre
    mysql_cursor.executemany(insert_movie_to_genre_command, movie_to_genre_list)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 192, in executemany
    self._get_db().encoding)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 229, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1062, u"Duplicate entry '1298584-\u5bb6\u5ead' for key 'PRIMARY'")
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 247, in insert_movie
    movie_release_date=movie['movie_release_date'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 282, in insert_movie_to_genre
    mysql_cursor.executemany(insert_movie_to_genre_command, movie_to_genre_list)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 192, in executemany
    self._get_db().encoding)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 229, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1062, u"Duplicate entry '1298584-\u5bb6\u5ead' for key 'PRIMARY'")
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 247, in insert_movie
    movie_release_date=movie['movie_release_date'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 282, in insert_movie_to_genre
    mysql_cursor.executemany(insert_movie_to_genre_command, movie_to_genre_list)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 192, in executemany
    self._get_db().encoding)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 229, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1062, u"Duplicate entry '1298584-\u5bb6\u5ead' for key 'PRIMARY'")
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 247, in insert_movie
    movie_release_date=movie['movie_release_date'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
Traceback (most recent call last):
  File "D:/own/auto_answer_for_movie/crawler/movie_crawler_new.py", line 282, in insert_movie_to_genre
    mysql_cursor.executemany(insert_movie_to_genre_command, movie_to_genre_list)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 192, in executemany
    self._get_db().encoding)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 229, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "D:\ruanjian\python27\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\ruanjian\python27\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
IntegrityError: (1062, u"Duplicate entry '1298584-\u5bb6\u5ead' for key 'PRIMARY'")
